### ISSUE TITLE
uid 和 uname 刚好反了一下，其他三处没有反

### ISSUE THREAD

**Issue by Huxzhi** [yulinfeng000/blive#4]
uid 和 uname 刚好反了一下，其他三处没有反

https://github.com/yulinfeng000/blive/blob/6a188c3b53a27016fd55e4b519e36a6df0a9e4a8/blive/msg.py#L187-L188

**Comment by yulinfeng000** [comment]
OK会尽快修复

**Comment by yulinfeng000** [comment]
已修复，`pip install -U blive` 升级blive修复这个bug
