### ISSUE TITLE
心跳包回复的数据前四位是人气值

### ISSUE THREAD

**Issue by wosiwq** [yulinfeng000/blive#8]
https://github.com/yulinfeng000/blive/blob/3cab5a65c4aa088562607f73692a4b344d3abf85/blive/core.py#L147
[这是说明](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/live/message_stream.md#%E5%BF%83%E8%B7%B3%E5%8C%85%E5%9B%9E%E5%A4%8D%E4%BA%BA%E6%B0%94%E5%80%BC)

可以使用 `struct.unpack("!I", data[:4])` 将其取出

**Comment by yulinfeng000** [comment]
好的，多谢

**Comment by wosiwq** [comment]
``` python
DEFAULT_POPULARITY = 1
popularity = struct.unpack("!I", data[:4])[0]
if popularity != DEFAULT_POPULARITY:
    packages.append(
        (header, f'{{"cmd": "HEARTBEAT", "popularity": {popularity}}}'))
```
我现在用这种方式把它模拟成一个cmd来把人气拿出来，有其他更优雅的实现方式吗？

**Comment by yulinfeng000** [comment]
已经改成通过cmd进行处理
```python

@app.on(Events.HEARTBEAT_REPLY)
async def liver_popularity(ctx):
    print(ctx.body['popularity'])

```
