### ISSUE TITLE
解析的时候有点问题

### ISSUE THREAD

**Issue by yuanbin3136** [yulinfeng000/blive#9]
偶尔会有弹幕数据出错

**Comment by yulinfeng000** [comment]
请提供详细的报错栈信息或者复现代码

**Comment by yuanbin3136** [comment]
![image](https://user-images.githubusercontent.com/11426715/223749239-f6f396a4-f841-4a34-a47b-d83621870090.png)
找到了，是直播间的独轮车脚本，有时候会带这几个符号，打印的时候就乱了。

**Comment by yulinfeng000** [comment]
\r 不属于是库的解析错误，你可以自己在监听的方法中处理掉

**Comment by yulinfeng000** [comment]
i will close this issue, if you have any question just reopen
